module tb_Comparator_4bit;
reg [3:0]a,b;
wire lt,eq,gt;
Comparator_4bit dut(a,b,lt,eq,gt);
initial
begin
$monitor("Time=0t a=%b b=%b lt=%b eq=%b gt=%b",$time,a,b,lt,eq,gt);
a=4'b0010; b=4'b1001; #10
a=4'b1110; b=4'b1001; #10
a=4'b0010; b=4'b1001; #10
a=4'b0000; b=4'b0000; #10
a=4'b1010; b=4'b1010; #10
a=4'b1101; b=4'b1001; #10
$finish;
end
endmodule